import { inflateRawSync } from "node:zlib";

/**
 * RESUME-002 — text extraction from PDF and DOCX.
 *
 * Deliberately implemented in-house with no third-party service. A resume is
 * the single most sensitive document a candidate gives us; sending it to an
 * external parser means a data processing agreement, a sub-processor
 * disclosure, and a promise about training that we would then have to police.
 * The extraction problem is tractable enough that avoiding all of that is worth
 * the code.
 *
 * AC-2 is the honest part: a scanned image-only PDF is DETECTED and flagged
 * MANUAL, not silently treated as an empty resume. Quietly producing an empty
 * profile from a real document is worse than admitting the limitation.
 */

export type Extraction = {
  text: string;
  status: "OK" | "MANUAL" | "FAILED";
  /** Why, in words a candidate can act on. */
  note: string | null;
  pages?: number;
};

/** AC-5 — cap the text so a pathological file cannot exhaust memory downstream. */
const MAX_CHARS = 200_000;

export function sniffMime(buf: Buffer): "pdf" | "docx" | "zip" | "unknown" {
  if (buf.length >= 5 && buf.subarray(0, 5).toString("latin1") === "%PDF-") return "pdf";
  // DOCX is a ZIP. "PK\x03\x04" alone is any zip; the content check happens in
  // extractDocx, which looks for word/document.xml specifically.
  if (buf.length >= 4 && buf[0] === 0x50 && buf[1] === 0x4b && buf[2] === 0x03 && buf[3] === 0x04) {
    return "zip";
  }
  return "unknown";
}

/**
 * RESUME-001 AC-5 — reject a PDF carrying executable content.
 *
 * A PDF with an OpenAction or embedded JavaScript is not a resume; it is a
 * delivery mechanism. We do not sanitize and serve — we refuse, because a
 * partially sanitized PDF that we then hand to a recruiter is our problem.
 */
export function pdfIsDangerous(buf: Buffer): { dangerous: boolean; reason: string | null } {
  const head = buf.subarray(0, Math.min(buf.length, 2_000_000)).toString("latin1");
  const checks: [RegExp, string][] = [
    [/\/JavaScript\b/, "embedded JavaScript"],
    [/\/JS\b/, "embedded JavaScript"],
    [/\/OpenAction\b/, "an automatic action that runs when the file is opened"],
    [/\/AA\b/, "automatic actions attached to the document"],
    [/\/Launch\b/, "a launch action"],
    [/\/EmbeddedFile\b/, "an embedded file"],
    [/\/RichMedia\b/, "embedded rich media"],
  ];
  for (const [re, reason] of checks) {
    if (re.test(head)) return { dangerous: true, reason };
  }
  return { dangerous: false, reason: null };
}

/**
 * Extract text from a PDF.
 *
 * Walks the raw structure rather than pulling in a parser dependency: find
 * content streams, inflate the FlateDecode ones, and read the text-showing
 * operators. This handles the overwhelming majority of resumes, which are
 * generated by Word, Google Docs, LaTeX or a CV builder and use simple text
 * operators with standard encodings.
 *
 * What it does NOT handle, and reports honestly rather than guessing at:
 *   • scanned/image-only PDFs (no text layer to find)
 *   • unusual CID font encodings with no ToUnicode mapping
 *   • encrypted PDFs
 */
export function extractPdf(buf: Buffer): Extraction {
  const danger = pdfIsDangerous(buf);
  if (danger.dangerous) {
    return {
      text: "",
      status: "FAILED",
      note: `This PDF contains ${danger.reason}, so we can't accept it. Please export a plain PDF from your word processor and upload that.`,
    };
  }

  if (/\/Encrypt\b/.test(buf.subarray(0, 200_000).toString("latin1"))) {
    return {
      text: "",
      status: "MANUAL",
      note: "This PDF is password-protected, so we can't read it. Save an unprotected copy, or fill in your profile by hand — either works.",
    };
  }

  const pages = (buf.toString("latin1").match(/\/Type\s*\/Page[^s]/g) ?? []).length || undefined;
  const chunks: string[] = [];

  // Inflate every FlateDecode stream; content streams are the ones with text.
  for (const stream of findStreams(buf)) {
    let data: Buffer;
    try {
      data = inflateRawSync(stripZlibHeader(stream));
    } catch {
      // Not deflate, or corrupt. Try the raw bytes — some producers emit
      // uncompressed content streams.
      data = stream;
    }
    const text = readTextOperators(data.toString("latin1"));
    if (text.trim()) chunks.push(text);
    if (chunks.join(" ").length > MAX_CHARS) break;
  }

  const text = normalise(chunks.join("\n"));

  if (text.length < 120) {
    // AC-2 — say so plainly rather than writing an empty profile.
    return {
      text,
      status: "MANUAL",
      note: "We couldn't find any readable text in this PDF — it looks like a scan or an image. You can still upload it for recruiters to read, but you'll need to fill in your profile yourself.",
      pages,
    };
  }

  return { text: text.slice(0, MAX_CHARS), status: "OK", note: null, pages };
}

/**
 * Extract text from a DOCX.
 *
 * A DOCX is a ZIP containing word/document.xml. Reads the central directory to
 * find that entry, inflates it, and strips the markup — preserving paragraph
 * and line breaks, because resume structure lives in the line breaks and
 * flattening them destroys the section detection downstream.
 */
export function extractDocx(buf: Buffer): Extraction {
  const entry = findZipEntry(buf, "word/document.xml");
  if (!entry) {
    return {
      text: "",
      status: "FAILED",
      note: "This file isn't a Word document we can read. Please upload a .docx or a PDF.",
    };
  }

  let xml: string;
  try {
    xml = (entry.method === 0 ? entry.data : inflateRawSync(entry.data)).toString("utf8");
  } catch {
    return {
      text: "",
      status: "FAILED",
      note: "We couldn't read this Word document — it may be corrupt. Try re-saving it, or upload a PDF.",
    };
  }

  const text = normalise(
    xml
      // Structure first, before the tags are gone.
      .replace(/<w:tab\b[^>]*\/?>/g, "\t")
      .replace(/<w:br\b[^>]*\/?>/g, "\n")
      .replace(/<\/w:p>/g, "\n")
      .replace(/<[^>]+>/g, "")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&amp;/g, "&")
      .replace(/&quot;/g, '"')
      .replace(/&apos;/g, "'")
      .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(Number(d)))
  );

  if (text.length < 60) {
    return {
      text,
      status: "MANUAL",
      note: "This document appears to be empty, or its content is all images. You'll need to fill in your profile yourself.",
    };
  }

  return { text: text.slice(0, MAX_CHARS), status: "OK", note: null };
}

export function extract(buf: Buffer): Extraction {
  const kind = sniffMime(buf);
  if (kind === "pdf") return extractPdf(buf);
  if (kind === "zip") return extractDocx(buf);
  return {
    text: "",
    status: "FAILED",
    note: "We only accept PDF and Word (.docx) files. That file is neither.",
  };
}

// ─────────────────────────────────────────────────────────────
// internals
// ─────────────────────────────────────────────────────────────

/** Locate every `stream … endstream` payload. */
function* findStreams(buf: Buffer): Generator<Buffer> {
  const hay = buf.toString("latin1");
  let i = 0;
  let found = 0;
  while (found < 500) {
    const start = hay.indexOf("stream", i);
    if (start === -1) return;
    // Skip the EOL after the keyword — CRLF or LF, per the spec.
    let s = start + 6;
    if (hay[s] === "\r") s++;
    if (hay[s] === "\n") s++;
    const end = hay.indexOf("endstream", s);
    if (end === -1) return;
    yield buf.subarray(s, end);
    i = end + 9;
    found++;
  }
}

/** inflateRawSync wants no zlib header; most PDF streams carry one. */
function stripZlibHeader(b: Buffer): Buffer {
  if (b.length > 2 && (b[0] & 0x0f) === 8 && ((b[0] << 8) | b[1]) % 31 === 0) {
    return b.subarray(2);
  }
  return b;
}

/**
 * Read the text-showing operators out of an inflated content stream.
 *
 * `(…) Tj`, `(…) '`, `(…) "` show a string. `[…] TJ` shows an array of strings
 * interleaved with kerning numbers, which are discarded. `TD`, `Td`, `T*` and
 * `ET` are line/paragraph boundaries and become newlines — without them the
 * whole resume collapses to one line and section detection fails.
 */
function readTextOperators(s: string): string {
  const out: string[] = [];
  const re = /\((?:\\.|[^\\()])*\)|\[(?:[^\]\\]|\\.)*\]|\bT[Dd*]\b|\bET\b|\bTJ\b|\bTj\b|'|"/g;
  let pending: string[] = [];

  for (const m of s.matchAll(re)) {
    const tok = m[0];
    if (tok.startsWith("(")) {
      pending.push(decodePdfString(tok.slice(1, -1)));
    } else if (tok.startsWith("[")) {
      for (const lit of tok.matchAll(/\((?:\\.|[^\\()])*\)/g)) {
        pending.push(decodePdfString(lit[0].slice(1, -1)));
      }
    } else if (tok === "TJ" || tok === "Tj" || tok === "'" || tok === '"') {
      if (pending.length) {
        out.push(pending.join(""));
        pending = [];
      }
    } else {
      // Positioning or end-of-text: a line break.
      if (pending.length) {
        out.push(pending.join(""));
        pending = [];
      }
      out.push("\n");
    }
  }
  if (pending.length) out.push(pending.join(""));
  return out.join("");
}

function decodePdfString(s: string): string {
  return s
    .replace(/\\n/g, "\n")
    .replace(/\\r/g, "\r")
    .replace(/\\t/g, "\t")
    .replace(/\\b/g, "\b")
    .replace(/\\f/g, "\f")
    .replace(/\\([0-7]{1,3})/g, (_, o) => String.fromCharCode(parseInt(o, 8)))
    .replace(/\\(.)/g, "$1");
}

type ZipEntry = { data: Buffer; method: number };

/**
 * Find one entry in a ZIP by walking local file headers.
 *
 * Bounded to 200 entries: a DOCX has a handful, and an archive with thousands
 * is either malicious or not a resume. This is the zip-bomb guard.
 */
function findZipEntry(buf: Buffer, name: string): ZipEntry | null {
  let off = 0;
  let seen = 0;
  while (off + 30 <= buf.length && seen < 200) {
    if (buf.readUInt32LE(off) !== 0x04034b50) break;
    const method = buf.readUInt16LE(off + 8);
    const compSize = buf.readUInt32LE(off + 18);
    const nameLen = buf.readUInt16LE(off + 26);
    const extraLen = buf.readUInt16LE(off + 28);
    const nameStart = off + 30;
    const entryName = buf.subarray(nameStart, nameStart + nameLen).toString("utf8");
    const dataStart = nameStart + nameLen + extraLen;

    // A streamed zip writes sizes to a trailing descriptor, so compSize is 0
    // here. Those are rare for DOCX; skip rather than guess at the length.
    if (compSize === 0 && entryName !== name) break;

    if (entryName === name) {
      const data = buf.subarray(dataStart, dataStart + compSize);
      // A single entry inflating to >64MB is a decompression bomb, not a resume.
      if (compSize > 32 * 1024 * 1024) return null;
      return { data, method };
    }
    off = dataStart + compSize;
    seen++;
  }
  return null;
}

/** Collapse whitespace without destroying the line structure. */
function normalise(s: string): string {
  return s
    .replace(/\r\n?/g, "\n")
    .replace(/[ \t ]+/g, " ")
    .replace(/ *\n */g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    // Strip control characters, which appear when a font encoding is unusual.
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, "")
    .trim();
}
